config/routes.rb
Rails.application.routes.draw do
  root "articles#index", as: "home"
  
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  http_basic_authenticate_with name: "taras", password: "0124816320", except: [:index, :show]
  
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end 

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "taras", password: "0124816320", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field(:title, {:class => 'form-control'}) %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area(:body, {:class => 'form-control'}) %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li>  <%= link_to home_path, class: "navbar-brand" do %>
        <%= image_tag "ww.png", alt:"taras", width:"30", height:"24", class:"d-inline-block align-text-top" %> BLOG
         <% end %>
         </li>
        <li> <%= link_to "New Article", new_article_path, class: "nav-link nav-link-right" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>My articles</h1>


  <% @articles.each do |a| %>
    <div class="well">
      <br/>
      <h3><%= a.title %></h3>
      <p><%= a.body %></p>
      <%= link_to 'Read More', a, class: "btn btn-secondary" %>
    </div>
  <% end %> 

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<div>
  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-secondary" %>
  <%= link_to "Destroy", article_path(@article), class:"btn btn-outline-danger",
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
</div>
              
<br>
<h3>Comments</h3>
<%= render @article.comments %>

<h3>Add a comment:</h3>
<%= render 'comments/form' %>
<br/>

app/views/comments/_comment.html.erb
<p>
 <strong> <%= comment.commenter %>:</strong>
  <%= comment.body %>


  <%= link_to 'Destroy Comment', [comment.article, comment],class:"btn btn-outline-danger btn-sm",
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field(:commenter, :class => 'form-control')%>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area(:body , :class => 'form-control')%>
  </p>
  <p>
    <%= form.submit(class:"btn btn-secondary") %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "articles/header" %>
  
  <div class="container">
    <br/>
    <%= yield %>
  </div>
  </body>
</html>